<form method="POST" action="<?php echo e(route('hse-incidents.update', $hseIncident)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?>
    <div class="row">
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Incident Code')); ?></label><input type="text" name="incident_code" value="<?php echo e($hseIncident->incident_code); ?>" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Title')); ?></label><input type="text" name="title" value="<?php echo e($hseIncident->title); ?>" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Category')); ?></label><input type="text" name="category" value="<?php echo e($hseIncident->category); ?>" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Reported By')); ?></label><select name="reported_by_employee_id" class="form-control"><option value=""><?php echo e(__('None')); ?></option><?php $__currentLoopData = $employees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>" <?php if((int) $hseIncident->reported_by_employee_id === (int) $id): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Severity')); ?></label><select name="severity" class="form-control"><?php $__currentLoopData = $severities; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>" <?php if($hseIncident->severity === $key): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>" <?php if($hseIncident->status === $key): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Occurred On')); ?></label><input type="date" name="occurred_on" value="<?php echo e($hseIncident->occurred_on); ?>" class="form-control"></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Location')); ?></label><input type="text" name="location" value="<?php echo e($hseIncident->location); ?>" class="form-control"></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Actions')); ?></label><textarea name="actions" class="form-control" rows="3"><?php echo e($hseIncident->actions); ?></textarea></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Notes')); ?></label><textarea name="notes" class="form-control" rows="3"><?php echo e($hseIncident->notes); ?></textarea></div>
    </div><div class="text-end"><button type="submit" class="btn btn-primary"><?php echo e(__('Update')); ?></button></div>
</form>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/hse_incidents/edit.blade.php ENDPATH**/ ?>