<form method="POST" action="<?php echo e(route('event-tickets.update', $eventTicket)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?>
    <div class="row">
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Event')); ?></label><select name="event_id" class="form-control"><?php $__currentLoopData = $events; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>" <?php if((int) $eventTicket->event_id === (int) $id): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Ticket Code')); ?></label><input type="text" name="ticket_code" value="<?php echo e($eventTicket->ticket_code); ?>" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Attendee Name')); ?></label><input type="text" name="attendee_name" value="<?php echo e($eventTicket->attendee_name); ?>" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Attendee Email')); ?></label><input type="email" name="attendee_email" value="<?php echo e($eventTicket->attendee_email); ?>" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Price')); ?></label><input type="number" step="0.01" name="price" value="<?php echo e($eventTicket->price); ?>" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>" <?php if($eventTicket->status === $key): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Checked In At')); ?></label><input type="datetime-local" name="checked_in_at" value="<?php echo e($eventTicket->checked_in_at ? \Carbon\Carbon::parse($eventTicket->checked_in_at)->format('Y-m-d\\TH:i') : ''); ?>" class="form-control"></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Notes')); ?></label><textarea name="notes" class="form-control" rows="3"><?php echo e($eventTicket->notes); ?></textarea></div>
    </div><div class="text-end"><button type="submit" class="btn btn-primary"><?php echo e(__('Update')); ?></button></div>
</form>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/event_tickets/edit.blade.php ENDPATH**/ ?>