<form method="POST" action="<?php echo e(route('microfinance-loans.update', $microfinanceLoan)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?>
    <div class="row">
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Customer')); ?></label><select name="customer_id" class="form-control"><?php $__currentLoopData = $customers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>" <?php if((int) $microfinanceLoan->customer_id === (int) $id): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Loan Number')); ?></label><input type="text" name="loan_number" value="<?php echo e($microfinanceLoan->loan_number); ?>" class="form-control" required></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Principal')); ?></label><input type="number" step="0.01" name="principal_amount" value="<?php echo e($microfinanceLoan->principal_amount); ?>" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Interest Rate')); ?></label><input type="number" step="0.01" name="interest_rate" value="<?php echo e($microfinanceLoan->interest_rate); ?>" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Installment')); ?></label><input type="number" step="0.01" name="installment_amount" value="<?php echo e($microfinanceLoan->installment_amount); ?>" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Start Date')); ?></label><input type="date" name="start_date" value="<?php echo e($microfinanceLoan->start_date); ?>" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Maturity Date')); ?></label><input type="date" name="maturity_date" value="<?php echo e($microfinanceLoan->maturity_date); ?>" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>" <?php if($microfinanceLoan->status === $key): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Purpose')); ?></label><input type="text" name="purpose" value="<?php echo e($microfinanceLoan->purpose); ?>" class="form-control"></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Notes')); ?></label><textarea name="notes" class="form-control" rows="3"><?php echo e($microfinanceLoan->notes); ?></textarea></div>
    </div><div class="text-end"><button type="submit" class="btn btn-primary"><?php echo e(__('Update')); ?></button></div>
</form>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/microfinance_loans/edit.blade.php ENDPATH**/ ?>