<?php $__env->startSection('page-title', __('Saved Views')); ?>
<?php $__env->startSection('page-subtitle', __('Store recurring filters, default list contexts and personal workspaces for repeated operations.')); ?>
<?php $__env->startSection('content'); ?>
<div class="row">
<div class="col-md-5"><div class="card ux-list-card"><div class="card-header"><h5><?php echo e(__('Create Saved View')); ?></h5></div><div class="card-body"><form method="POST" action="<?php echo e(route('core.saved-views.store')); ?>"><?php echo csrf_field(); ?> <div class="mb-3"><label class="form-label"><?php echo e(__('Module key')); ?></label><input type="text" name="module" class="form-control" placeholder="<?php echo e(__('invoice, projects, leads...')); ?>" required></div><div class="mb-3"><label class="form-label"><?php echo e(__('View name')); ?></label><input type="text" name="name" class="form-control" placeholder="<?php echo e(__('Month-end receivables')); ?>" required></div><div class="mb-3"><label class="form-label"><?php echo e(__('Primary filter')); ?></label><input type="text" name="filters[search]" class="form-control" placeholder="<?php echo e(__('Overdue, urgent, active...')); ?>"></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_default" value="1"><label class="form-check-label"><?php echo e(__('Default view')); ?></label></div><button class="btn btn-primary w-100"><?php echo e(__('Save View')); ?></button></form></div></div></div>
<div class="col-md-7"><div class="card ux-list-card"><div class="card-header"><h5><?php echo e(__('My Saved Views')); ?></h5></div><div class="card-body"><table class="table"><thead><tr><th><?php echo e(__('Module')); ?></th><th><?php echo e(__('Name')); ?></th><th><?php echo e(__('Filters')); ?></th><th><?php echo e(__('Default')); ?></th><th></th></tr></thead><tbody><?php $__empty_2 = true; $__currentLoopData = $views; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $view): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_2 = false; ?><tr><td><strong><?php echo e($view->module); ?></strong></td><td><?php echo e($view->name); ?></td><td><span class="text-muted small"><?php echo e(data_get($view->payload, 'filters.search', __('No quick filter'))); ?></span></td><td><?php echo e($view->is_default ? __('Yes') : __('No')); ?></td><td><form method="POST" action="<?php echo e(route('core.saved-views.destroy', $view)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-danger"><?php echo e(__('Delete')); ?></button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_2): ?><tr><td colspan="5" class="text-muted"><?php echo e(__('No saved views yet.')); ?></td></tr><?php endif; ?></tbody></table></div></div></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/core_platform/saved_views.blade.php ENDPATH**/ ?>