<div class="row">
    <div class="col-md-6 mb-3"><label class="form-label"><?php echo e(__('Name')); ?></label><input type="text" name="name" class="form-control" value="<?php echo e(old('name', $npsCampaign->name ?? '')); ?>" required></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Channel')); ?></label><input type="text" name="channel" class="form-control" value="<?php echo e(old('channel', $npsCampaign->channel ?? 'email')); ?>" required></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $statusKey => $statusLabel): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($statusKey); ?>" <?php if(old('status', $npsCampaign->status ?? 'draft') == $statusKey): echo 'selected'; endif; ?>><?php echo e(__($statusLabel)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Audience')); ?></label><input type="text" name="audience_type" class="form-control" value="<?php echo e(old('audience_type', $npsCampaign->audience_type ?? 'customers')); ?>"></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Sent at')); ?></label><input type="datetime-local" name="sent_at" class="form-control" value="<?php echo e(old('sent_at', isset($npsCampaign) && $npsCampaign->sent_at ? \Carbon\Carbon::parse($npsCampaign->sent_at)->format('Y-m-d\\TH:i') : '')); ?>"></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Closes at')); ?></label><input type="datetime-local" name="closes_at" class="form-control" value="<?php echo e(old('closes_at', isset($npsCampaign) && $npsCampaign->closes_at ? \Carbon\Carbon::parse($npsCampaign->closes_at)->format('Y-m-d\\TH:i') : '')); ?>"></div>
    <div class="col-md-12 mb-3"><label class="form-label"><?php echo e(__('Description')); ?></label><textarea name="description" class="form-control" rows="4"><?php echo e(old('description', $npsCampaign->description ?? '')); ?></textarea></div>
</div>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/nps_campaigns/_form.blade.php ENDPATH**/ ?>