<?php $__env->startSection('page-title'); ?><?php echo e(__('Quality Plans')); ?><?php $__env->stopSection(); ?>
<?php $__env->startSection('breadcrumb'); ?>
    <li class="breadcrumb-item"><a href="<?php echo e(route('dashboard')); ?>"><?php echo e(__('Dashboard')); ?></a></li>
    <li class="breadcrumb-item"><?php echo e(__('Production')); ?></li>
    <li class="breadcrumb-item"><?php echo e(__('Quality Plans')); ?></li>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('action-btn'); ?>
    <div class="float-end"><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create industrial quality plan')): ?><a href="#" data-size="lg" data-url="<?php echo e(route('production.quality-plans.create')); ?>" data-ajax-popup="true" data-title="<?php echo e(__('Create Quality Plan')); ?>" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a><?php endif; ?></div>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?>
    <div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable">
        <thead><tr><th><?php echo e(__('Name')); ?></th><th><?php echo e(__('Product')); ?></th><th><?php echo e(__('Routing')); ?></th><th><?php echo e(__('Stage')); ?></th><th><?php echo e(__('Status')); ?></th><th><?php echo e(__('Action')); ?></th></tr></thead>
        <tbody><?php $__currentLoopData = $qualityPlans; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $qualityPlan): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><?php echo e($qualityPlan->name); ?></td><td><?php echo e($qualityPlan->product?->name ?: '-'); ?></td><td><?php echo e($qualityPlan->routing?->name ?: '-'); ?></td><td><?php echo e(ucfirst(str_replace('_',' ', $qualityPlan->check_stage))); ?></td><td><?php echo e(ucfirst($qualityPlan->status)); ?></td><td class="Action"><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('edit industrial quality plan')): ?><div class="action-btn me-2"><a href="#" class="mx-3 btn btn-sm align-items-center bg-info" data-url="<?php echo e(route('production.quality-plans.edit', $qualityPlan->id)); ?>" data-ajax-popup="true" data-size="lg"><i class="ti ti-pencil text-white"></i></a></div><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete industrial quality plan')): ?><div class="action-btn"><?php echo Form::open(['method'=>'DELETE','route'=>['production.quality-plans.destroy',$qualityPlan->id],'id'=>'delete-form-quality-'.$qualityPlan->id]); ?><a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger"><i class="ti ti-trash text-white"></i></a><?php echo Form::close(); ?></div><?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody>
    </table></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/production/quality_plans/index.blade.php ENDPATH**/ ?>