<?php echo e(Form::model($dispensation, ['route' => ['pharmacy-dispensations.update', $dispensation->id], 'method' => 'put'])); ?>

<div class="modal-body"><div class="row">
    <div class="col-md-6"><label class="form-label"><?php echo e(__('Patient')); ?></label><select name="patient_id" class="form-control" required><?php $__currentLoopData = $patients; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $patient): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($patient->id); ?>" <?php echo e($dispensation->patient_id == $patient->id ? 'selected' : ''); ?>><?php echo e($patient->first_name); ?> <?php echo e($patient->last_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6"><?php echo e(Form::label('status', __('Status'), ['class' => 'form-label'])); ?><?php echo e(Form::select('status', ['dispensed' => __('Dispensed'), 'returned' => __('Returned')], $dispensation->status, ['class' => 'form-control'])); ?></div>
    <div class="col-md-6 mt-2"><label class="form-label"><?php echo e(__('Consultation')); ?></label><select name="consultation_id" class="form-control"><option value=""><?php echo e(__('Select consultation')); ?></option><?php $__currentLoopData = $consultations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $consultation): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($consultation->id); ?>" <?php echo e($dispensation->consultation_id == $consultation->id ? 'selected' : ''); ?>><?php echo e(optional($consultation->patient)->first_name); ?> <?php echo e(optional($consultation->patient)->last_name); ?> - <?php echo e(\Auth::user()->dateFormat($consultation->consultation_date)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6 mt-2"><label class="form-label"><?php echo e(__('Prescription')); ?></label><select name="prescription_id" class="form-control"><option value=""><?php echo e(__('Select prescription')); ?></option><?php $__currentLoopData = $prescriptions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $prescription): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($prescription->id); ?>" <?php echo e($dispensation->prescription_id == $prescription->id ? 'selected' : ''); ?>><?php echo e($prescription->medication_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-12 mt-2"><?php echo e(Form::label('dispensed_at', __('Dispensed At'), ['class' => 'form-label'])); ?><?php echo e(Form::datetimeLocal('dispensed_at', $dispensation->dispensed_at?->format('Y-m-d\TH:i'), ['class' => 'form-control'])); ?></div>
    <?php ($items = $dispensation->items->values()); ?>
    <?php for($i = 0; $i < max(3, $items->count()); $i++): ?>
        <div class="col-md-4 mt-3"><label class="form-label"><?php echo e(__('Medication')); ?> <?php echo e($i + 1); ?></label><select name="items[<?php echo e($i); ?>][pharmacy_medication_id]" class="form-control"><option value=""><?php echo e(__('Select medication')); ?></option><?php $__currentLoopData = $medications; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $medication): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($medication->id); ?>" <?php echo e(optional($items->get($i))->pharmacy_medication_id == $medication->id ? 'selected' : ''); ?>><?php echo e($medication->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-2 mt-3"><?php echo e(Form::label("items[$i][quantity]", __('Qty'), ['class' => 'form-label'])); ?><?php echo e(Form::number("items[$i][quantity]", $items->get($i)->quantity ?? 1, ['class' => 'form-control', 'step' => '0.01'])); ?></div>
        <div class="col-md-2 mt-3"><?php echo e(Form::label("items[$i][dosage]", __('Dosage'), ['class' => 'form-label'])); ?><?php echo e(Form::text("items[$i][dosage]", $items->get($i)->dosage ?? null, ['class' => 'form-control'])); ?></div>
        <div class="col-md-2 mt-3"><?php echo e(Form::label("items[$i][frequency]", __('Frequency'), ['class' => 'form-label'])); ?><?php echo e(Form::text("items[$i][frequency]", $items->get($i)->frequency ?? null, ['class' => 'form-control'])); ?></div>
        <div class="col-md-2 mt-3"><?php echo e(Form::label("items[$i][duration]", __('Duration'), ['class' => 'form-label'])); ?><?php echo e(Form::text("items[$i][duration]", $items->get($i)->duration ?? null, ['class' => 'form-control'])); ?></div>
    <?php endfor; ?>
    <div class="col-12 mt-3"><?php echo e(Form::label('notes', __('Notes'), ['class' => 'form-label'])); ?><?php echo e(Form::textarea('notes', null, ['class' => 'form-control', 'rows' => 2])); ?></div>
</div></div>
<div class="modal-footer"><input type="button" value="<?php echo e(__('Cancel')); ?>" class="btn btn-secondary" data-bs-dismiss="modal"><input type="submit" value="<?php echo e(__('Update')); ?>" class="btn btn-primary"></div>
<?php echo e(Form::close()); ?>

<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/pharmacy_dispensation/edit.blade.php ENDPATH**/ ?>