<?php $__env->startSection('page-title', $savedReport->name); ?>
<?php $__env->startSection('page-subtitle', __('Run saved reports on demand and schedule digest delivery for decision makers.')); ?>
<?php $__env->startSection('content'); ?>
<div class="row">
<div class="col-md-8">
    <div class="row mb-3">
        <div class="col-md-4"><div class="card"><div class="card-body"><span class="text-muted d-block small"><?php echo e(__('Rows')); ?></span><h3 class="mb-0"><?php echo e($result['count']); ?></h3></div></div></div>
        <div class="col-md-4"><div class="card"><div class="card-body"><span class="text-muted d-block small"><?php echo e(__('Columns')); ?></span><h3 class="mb-0"><?php echo e(count($result['columns'])); ?></h3></div></div></div>
        <div class="col-md-4"><div class="card"><div class="card-body"><span class="text-muted d-block small"><?php echo e(__('Last Run')); ?></span><h6 class="mb-0"><?php echo e(optional($savedReport->last_run_at)->diffForHumans() ?: __('Just now')); ?></h6></div></div></div>
    </div>
    <div class="card"><div class="card-header"><h5><?php echo e(__('Report Result')); ?></h5></div><div class="card-body table-border-style"><table class="table"><thead><tr><?php $__currentLoopData = $result['columns']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $column): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><th><?php echo e($column); ?></th><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr></thead><tbody><?php $__empty_2 = true; $__currentLoopData = $result['rows']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_2 = false; ?><tr><?php $__currentLoopData = $result['columns']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $column): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><td><?php echo e(data_get($row, $column)); ?></td><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_2): ?><tr><td colspan="<?php echo e(max(count($result['columns']),1)); ?>" class="text-muted"><?php echo e(__('No rows found.')); ?></td></tr><?php endif; ?></tbody></table></div></div>
</div>
<div class="col-md-4"><div class="card mb-3"><div class="card-header"><h5><?php echo e(__('Schedule by Email')); ?></h5></div><div class="card-body"><form method="POST" action="<?php echo e(route('core.reports.schedule', $savedReport)); ?>"><?php echo csrf_field(); ?> <div class="mb-2"><label class="form-label"><?php echo e(__('Name')); ?></label><input type="text" name="name" class="form-control" required></div><div class="mb-2"><label class="form-label"><?php echo e(__('Frequency')); ?></label><select name="frequency" class="form-control"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></div><div class="mb-2"><label class="form-label"><?php echo e(__('Recipients')); ?></label><input type="text" name="recipients" class="form-control" placeholder="a@b.com,c@d.com" required></div><button class="btn btn-primary"><?php echo e(__('Save Schedule')); ?></button></form></div></div><div class="card"><div class="card-header"><h5><?php echo e(__('Existing Schedules')); ?></h5></div><div class="card-body"><?php $__empty_2 = true; $__currentLoopData = $schedules; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $schedule): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_2 = false; ?><div class="border rounded p-2 mb-2 d-flex justify-content-between align-items-center"><div><div class="fw-semibold"><?php echo e($schedule->name); ?></div><small class="text-muted"><?php echo e(ucfirst($schedule->frequency)); ?> • <?php echo e(implode(', ', $schedule->recipients ?? [])); ?></small></div><form method="POST" action="<?php echo e(route('core.reports.schedule.toggle', $schedule)); ?>"><?php echo csrf_field(); ?> <button class="btn btn-sm <?php echo e($schedule->is_active ? 'btn-warning' : 'btn-success'); ?>"><?php echo e($schedule->is_active ? __('Pause') : __('Resume')); ?></button></form></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_2): ?><div class="text-muted"><?php echo e(__('No schedules configured.')); ?></div><?php endif; ?></div></div></div>
<div class="col-md-4"><div class="card mb-3"><div class="card-header"><h5><?php echo e(__('Schedule by Email')); ?></h5></div><div class="card-body"><form method="POST" action="<?php echo e(route('core.reports.schedule', $savedReport)); ?>"><?php echo csrf_field(); ?> <div class="mb-2"><label class="form-label"><?php echo e(__('Name')); ?></label><input type="text" name="name" class="form-control" required></div><div class="mb-2"><label class="form-label"><?php echo e(__('Frequency')); ?></label><select name="frequency" class="form-control"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></div><div class="mb-2"><label class="form-label"><?php echo e(__('Recipients')); ?></label><input type="text" name="recipients" class="form-control" placeholder="a@b.com,c@d.com" required></div><button class="btn btn-primary"><?php echo e(__('Save Schedule')); ?></button></form></div></div><div class="card"><div class="card-header"><h5><?php echo e(__('Existing Schedules')); ?></h5></div><div class="card-body"><?php $__empty_2 = true; $__currentLoopData = $schedules; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $schedule): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_2 = false; ?><div class="border rounded p-2 mb-2"><div class="d-flex justify-content-between align-items-start gap-2"><div><div class="fw-semibold"><?php echo e($schedule->name); ?></div><small class="text-muted"><?php echo e(ucfirst($schedule->frequency)); ?> • <?php echo e(implode(', ', $schedule->recipients ?? [])); ?></small><div class="small text-muted mt-1"><?php echo e(__('Last sent')); ?>: <?php echo e(optional($schedule->last_sent_at)->diffForHumans() ?: __('Never')); ?></div></div><div class="d-flex gap-2"><form method="POST" action="<?php echo e(route('core.reports.schedule.send', $schedule)); ?>"><?php echo csrf_field(); ?> <button class="btn btn-sm btn-light"><?php echo e(__('Send now')); ?></button></form><form method="POST" action="<?php echo e(route('core.reports.schedule.toggle', $schedule)); ?>"><?php echo csrf_field(); ?> <button class="btn btn-sm <?php echo e($schedule->is_active ? 'btn-warning' : 'btn-success'); ?>"><?php echo e($schedule->is_active ? __('Pause') : __('Resume')); ?></button></form></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_2): ?><div class="text-muted"><?php echo e(__('No schedules configured.')); ?></div><?php endif; ?></div></div></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/core_data/report_show.blade.php ENDPATH**/ ?>