<form method="POST" action="<?php echo e(route('transport-shipments.store')); ?>"><?php echo csrf_field(); ?>
    <div class="row">
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Reference')); ?></label><input type="text" name="reference" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Customer')); ?></label><select name="customer_id" class="form-control"><option value=""><?php echo e(__('None')); ?></option><?php $__currentLoopData = $customers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>"><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Origin')); ?></label><input type="text" name="origin" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Destination')); ?></label><input type="text" name="destination" class="form-control" required></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Vehicle Number')); ?></label><input type="text" name="vehicle_number" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Driver Name')); ?></label><input type="text" name="driver_name" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>"><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Departure Date')); ?></label><input type="date" name="departure_date" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Arrival Date')); ?></label><input type="date" name="arrival_date" class="form-control"></div>
        <div class="col-md-4 form-group"><label class="form-label"><?php echo e(__('Freight Amount')); ?></label><input type="number" step="0.01" name="freight_amount" class="form-control"></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Notes')); ?></label><textarea name="notes" class="form-control" rows="3"></textarea></div>
    </div><div class="text-end"><button type="submit" class="btn btn-primary"><?php echo e(__('Create')); ?></button></div>
</form>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/transport_shipments/create.blade.php ENDPATH**/ ?>