<?php $__env->startSection('page-title', $okrObjective->title); ?>
<?php $__env->startSection('breadcrumb'); ?>
    <li class="breadcrumb-item"><a href="<?php echo e(route('dashboard')); ?>"><?php echo e(__('Dashboard')); ?></a></li>
    <li class="breadcrumb-item"><a href="<?php echo e(route('okr-objectives.index')); ?>"><?php echo e(__('OKR Workspace')); ?></a></li>
    <li class="breadcrumb-item"><?php echo e($okrObjective->title); ?></li>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?>
    <div class="ux-kpi-grid mb-4">
        <div class="ux-kpi-card"><span class="ux-kpi-label"><?php echo e(__('Progress')); ?></span><strong class="ux-kpi-value"><?php echo e(number_format((float) $okrObjective->progress, 0)); ?>%</strong><span class="ux-kpi-meta"><?php echo e(__('objective completion')); ?></span></div>
        <div class="ux-kpi-card"><span class="ux-kpi-label"><?php echo e(__('Key Results')); ?></span><strong class="ux-kpi-value"><?php echo e($okrObjective->keyResults->count()); ?></strong><span class="ux-kpi-meta"><?php echo e(__('tracked metrics')); ?></span></div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="card"><div class="card-body"><h5><?php echo e(__('Objective Summary')); ?></h5><p class="text-muted mb-2"><?php echo e($okrObjective->description ?: __('No description provided.')); ?></p><div><strong><?php echo e(__('Owner')); ?>:</strong> <?php echo e(optional($okrObjective->owner)->name ?: '-'); ?></div><div><strong><?php echo e(__('Cycle')); ?>:</strong> <?php echo e($okrObjective->cycle ?: '-'); ?></div><div><strong><?php echo e(__('Status')); ?>:</strong> <?php echo e(__(ucfirst(str_replace('_', ' ', $okrObjective->status)))); ?></div></div></div>
            <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create okr key result')): ?>
                <div class="card"><div class="card-body"><h5><?php echo e(__('Add Key Result')); ?></h5><form method="POST" action="<?php echo e(route('okr-key-results.store', $okrObjective)); ?>"><?php echo csrf_field(); ?>
                    <div class="mb-3"><label class="form-label"><?php echo e(__('Metric')); ?></label><input type="text" name="metric_name" class="form-control" required></div>
                    <div class="row"><div class="col-md-4 mb-3"><label class="form-label"><?php echo e(__('Start')); ?></label><input type="number" step="0.01" name="start_value" class="form-control" value="0"></div><div class="col-md-4 mb-3"><label class="form-label"><?php echo e(__('Target')); ?></label><input type="number" step="0.01" name="target_value" class="form-control" required></div><div class="col-md-4 mb-3"><label class="form-label"><?php echo e(__('Current')); ?></label><input type="number" step="0.01" name="current_value" class="form-control" value="0"></div></div>
                    <div class="row"><div class="col-md-6 mb-3"><label class="form-label"><?php echo e(__('Unit')); ?></label><input type="text" name="unit" class="form-control"></div><div class="col-md-6 mb-3"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $keyResultStatuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $statusKey => $statusLabel): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($statusKey); ?>"><?php echo e(__($statusLabel)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div></div>
                    <div class="mb-3"><label class="form-label"><?php echo e(__('Due date')); ?></label><input type="date" name="due_date" class="form-control"></div>
                    <button type="submit" class="btn btn-primary"><?php echo e(__('Add key result')); ?></button></form></div></div>
            <?php endif; ?>
        </div>
        <div class="col-lg-8">
            <div class="card ux-list-card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table"><thead><tr><th><?php echo e(__('Metric')); ?></th><th><?php echo e(__('Progress')); ?></th><th><?php echo e(__('Status')); ?></th><th><?php echo e(__('Action')); ?></th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $okrObjective->keyResults; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $keyResult): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><div><?php echo e($keyResult->metric_name); ?></div><small class="text-muted"><?php echo e($keyResult->unit ?: __('No unit')); ?></small></td><td><?php echo e($keyResult->current_value); ?> / <?php echo e($keyResult->target_value); ?></td><td><span class="badge bg-info"><?php echo e(__(ucfirst(str_replace('_', ' ', $keyResult->status)))); ?></span></td><td class="Action"><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('edit okr key result')): ?><div class="action-btn me-2"><a href="<?php echo e(route('okr-key-results.edit', $keyResult)); ?>" class="mx-3 btn btn-sm bg-info"><i class="ti ti-pencil text-white"></i></a></div><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete okr key result')): ?><div class="action-btn"><form method="POST" action="<?php echo e(route('okr-key-results.destroy', $keyResult)); ?>" id="delete-key-result-<?php echo e($keyResult->id); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><a href="#" class="mx-3 btn btn-sm bg-danger bs-pass-para" data-confirm="<?php echo e(__('Are You Sure?').'|'.__('This action can not be undone. Do you want to continue?')); ?>" data-confirm-yes="document.getElementById('delete-key-result-<?php echo e($keyResult->id); ?>').submit();"><i class="ti ti-trash text-white"></i></a></form></div><?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4" class="text-center text-muted"><?php echo e(__('No key results created yet.')); ?></td></tr><?php endif; ?></tbody></table></div></div></div>
        </div>
    </div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/okr_objectives/show.blade.php ENDPATH**/ ?>