<?php echo e(Form::open(['route' => 'medical-invoices.store', 'method' => 'post'])); ?>

<div class="modal-body"><div class="row">
    <div class="col-md-6"><label class="form-label"><?php echo e(__('Patient')); ?></label><select name="patient_id" class="form-control" required><option value=""><?php echo e(__('Select patient')); ?></option><?php $__currentLoopData = $patients; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $patient): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($patient->id); ?>"><?php echo e($patient->first_name); ?> <?php echo e($patient->last_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6"><label class="form-label"><?php echo e(__('Status')); ?></label><?php echo e(Form::select('status', ['draft' => __('Draft'), 'unpaid' => __('Unpaid'), 'partial' => __('Partial'), 'paid' => __('Paid')], 'draft', ['class' => 'form-control'])); ?></div>
    <div class="col-md-6 mt-2"><label class="form-label"><?php echo e(__('Consultation')); ?></label><select name="consultation_id" class="form-control"><option value=""><?php echo e(__('Select consultation')); ?></option><?php $__currentLoopData = $consultations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $consultation): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($consultation->id); ?>"><?php echo e(optional($consultation->patient)->first_name); ?> <?php echo e(optional($consultation->patient)->last_name); ?> - <?php echo e(\Auth::user()->dateFormat($consultation->consultation_date)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6 mt-2"><label class="form-label"><?php echo e(__('Appointment')); ?></label><select name="appointment_id" class="form-control"><option value=""><?php echo e(__('Select appointment')); ?></option><?php $__currentLoopData = $appointments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $appointment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($appointment->id); ?>"><?php echo e(optional($appointment->patient)->first_name); ?> <?php echo e(optional($appointment->patient)->last_name); ?> - <?php echo e(\Auth::user()->dateFormat($appointment->start_at)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6 mt-2"><?php echo e(Form::label('invoice_date', __('Invoice Date'), ['class' => 'form-label'])); ?><?php echo e(Form::date('invoice_date', now()->format('Y-m-d'), ['class' => 'form-control', 'required' => 'required'])); ?></div>
    <div class="col-md-6 mt-2"><?php echo e(Form::label('due_date', __('Due Date'), ['class' => 'form-label'])); ?><?php echo e(Form::date('due_date', null, ['class' => 'form-control'])); ?></div>
    <div class="col-md-12 mt-2"><?php echo e(Form::label('insurer_name', __('Insurer / Mutual'), ['class' => 'form-label'])); ?><?php echo e(Form::text('insurer_name', null, ['class' => 'form-control'])); ?></div>
    <?php for($i = 0; $i < 3; $i++): ?>
        <div class="col-md-4 mt-3"><label class="form-label"><?php echo e(__('Medical Service')); ?> <?php echo e($i + 1); ?></label><select name="items[<?php echo e($i); ?>][medical_service_id]" class="form-control"><option value=""><?php echo e(__('Select service')); ?></option><?php $__currentLoopData = $services; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $service): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($service->id); ?>"><?php echo e($service->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-4 mt-3"><?php echo e(Form::label("items[$i][description]", __('Description'), ['class' => 'form-label'])); ?><?php echo e(Form::text("items[$i][description]", null, ['class' => 'form-control'])); ?></div>
        <div class="col-md-2 mt-3"><?php echo e(Form::label("items[$i][quantity]", __('Qty'), ['class' => 'form-label'])); ?><?php echo e(Form::number("items[$i][quantity]", 1, ['class' => 'form-control', 'step' => '0.01'])); ?></div>
        <div class="col-md-2 mt-3"><?php echo e(Form::label("items[$i][unit_price]", __('Price'), ['class' => 'form-label'])); ?><?php echo e(Form::number("items[$i][unit_price]", 0, ['class' => 'form-control', 'step' => '0.01'])); ?></div>
        <div class="col-md-12 mt-2"><?php echo e(Form::label("items[$i][coverage_rate]", __('Coverage %'), ['class' => 'form-label'])); ?><?php echo e(Form::number("items[$i][coverage_rate]", 0, ['class' => 'form-control', 'step' => '0.01'])); ?></div>
    <?php endfor; ?>
    <div class="col-12 mt-3"><?php echo e(Form::label('notes', __('Notes'), ['class' => 'form-label'])); ?><?php echo e(Form::textarea('notes', null, ['class' => 'form-control', 'rows' => 2])); ?></div>
</div></div>
<div class="modal-footer"><input type="button" value="<?php echo e(__('Cancel')); ?>" class="btn btn-secondary" data-bs-dismiss="modal"><input type="submit" value="<?php echo e(__('Create')); ?>" class="btn btn-primary"></div>
<?php echo e(Form::close()); ?>

<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/medical_invoice/create.blade.php ENDPATH**/ ?>