<?php $__env->startSection('page-title', __('API Clients')); ?>
<?php $__env->startSection('page-subtitle', __('Issue dedicated credentials, inspect traffic and govern partner integrations.')); ?>
<?php $__env->startSection('action-btn'); ?><div class="d-flex gap-2"><a href="<?php echo e(route('api-clients.docs')); ?>" class="btn btn-sm btn-light"><?php echo e(__('Docs')); ?></a><a href="<?php echo e(route('api-clients.create')); ?>" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a></div><?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?>
<div class="row mb-3">
    <div class="col-md-3"><div class="card"><div class="card-body"><h6><?php echo e(__('Clients')); ?></h6><h3><?php echo e($stats['clients']); ?></h3></div></div></div>
    <div class="col-md-3"><div class="card"><div class="card-body"><h6><?php echo e(__('Recent API Calls')); ?></h6><h3><?php echo e($recentLogs->count()); ?></h3></div></div></div>
    <div class="col-md-3"><div class="card"><div class="card-body"><h6><?php echo e(__('Active Keys')); ?></h6><h3><?php echo e($stats['active']); ?></h3></div></div></div>
    <div class="col-md-3"><div class="card"><div class="card-body"><h6><?php echo e(__('Failed Calls')); ?></h6><h3><?php echo e($stats['failedCalls']); ?></h3></div></div></div>
</div>
<div class="card mb-3"><div class="card-body table-border-style"><table class="table"><thead><tr><th><?php echo e(__('Name')); ?></th><th><?php echo e(__('Key')); ?></th><th><?php echo e(__('Status')); ?></th><th><?php echo e(__('Usage')); ?></th><th><?php echo e(__('Last Used')); ?></th><th><?php echo e(__('Expires')); ?></th><th><?php echo e(__('Action')); ?></th></tr></thead><tbody><?php $__currentLoopData = $clients; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $client): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><?php echo e($client->name); ?></td><td><code><?php echo e($client->client_key); ?></code></td><td><span class="badge <?php echo e($client->is_active ? 'bg-success' : 'bg-danger'); ?>"><?php echo e($client->is_active ? __('Active') : __('Inactive')); ?></span></td><td><?php echo e($client->logs_count); ?></td><td><?php echo e(optional($client->last_used_at)->diffForHumans() ?: '-'); ?></td><td><?php echo e(optional($client->expires_at)->format('Y-m-d') ?: '-'); ?></td><td><div class="d-flex gap-2 flex-wrap"><a href="<?php echo e(route('api-clients.show', $client)); ?>" class="btn btn-sm btn-light"><?php echo e(__('Open')); ?></a><form method="POST" action="<?php echo e(route('api-clients.toggle-status', $client)); ?>"><?php echo csrf_field(); ?> <button class="btn btn-sm btn-secondary"><?php echo e($client->is_active ? __('Disable') : __('Enable')); ?></button></form><form method="POST" action="<?php echo e(route('api-clients.destroy', $client)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-danger"><?php echo e(__('Delete')); ?></button></form></div></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div></div>
<div class="card"><div class="card-header"><h5 class="mb-0"><?php echo e(__('Recent API Logs')); ?></h5></div><div class="card-body table-border-style"><table class="table"><thead><tr><th><?php echo e(__('When')); ?></th><th><?php echo e(__('Client')); ?></th><th><?php echo e(__('Route')); ?></th><th><?php echo e(__('Status')); ?></th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $recentLogs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $log): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e(optional($log->requested_at)->format('Y-m-d H:i')); ?></td><td><?php echo e(optional($log->apiClient)->name ?: '-'); ?></td><td><code><?php echo e($log->route); ?></code></td><td><?php echo e($log->status_code ?: '-'); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4" class="text-center text-muted"><?php echo e(__('No API logs captured yet.')); ?></td></tr><?php endif; ?></tbody></table></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/api_client/index.blade.php ENDPATH**/ ?>