<form method="POST" action="<?php echo e(route('product-lifecycle-records.update', $productLifecycleRecord)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?>
    <div class="row">
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Product')); ?></label><select name="product_service_id" class="form-control"><?php $__currentLoopData = $products; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>" <?php if((int) $productLifecycleRecord->product_service_id === (int) $id): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Owner')); ?></label><select name="owner_employee_id" class="form-control"><option value=""><?php echo e(__('None')); ?></option><?php $__currentLoopData = $employees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>" <?php if((int) $productLifecycleRecord->owner_employee_id === (int) $id): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Stage')); ?></label><select name="stage" class="form-control"><?php $__currentLoopData = $stages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>" <?php if($productLifecycleRecord->stage === $key): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>" <?php if($productLifecycleRecord->status === $key): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Effective Date')); ?></label><input type="date" name="effective_date" value="<?php echo e($productLifecycleRecord->effective_date); ?>" class="form-control"></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Compliance Status')); ?></label><input type="text" name="compliance_status" value="<?php echo e($productLifecycleRecord->compliance_status); ?>" class="form-control"></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Notes')); ?></label><textarea name="notes" class="form-control" rows="3"><?php echo e($productLifecycleRecord->notes); ?></textarea></div>
    </div><div class="text-end"><button type="submit" class="btn btn-primary"><?php echo e(__('Update')); ?></button></div>
</form>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/product_lifecycle_records/edit.blade.php ENDPATH**/ ?>