<div class="row">
    <div class="col-md-6 mb-3"><label class="form-label"><?php echo e(__('Title')); ?></label><input type="text" name="title" class="form-control" value="<?php echo e(old('title', $okrObjective->title ?? '')); ?>" required></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Owner')); ?></label><select name="owner_id" class="form-control"><option value=""><?php echo e(__('Select owner')); ?></option><?php $__currentLoopData = $owners; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $ownerId => $ownerName): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($ownerId); ?>" <?php if(old('owner_id', $okrObjective->owner_id ?? '') == $ownerId): echo 'selected'; endif; ?>><?php echo e($ownerName); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Linked project')); ?></label><select name="project_id" class="form-control"><option value=""><?php echo e(__('Optional')); ?></option><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $projectId => $projectName): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($projectId); ?>" <?php if(old('project_id', $okrObjective->project_id ?? '') == $projectId): echo 'selected'; endif; ?>><?php echo e($projectName); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Cycle')); ?></label><input type="text" name="cycle" class="form-control" value="<?php echo e(old('cycle', $okrObjective->cycle ?? '')); ?>" placeholder="<?php echo e(__('Q2 2026')); ?>"></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $statusKey => $statusLabel): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($statusKey); ?>" <?php if(old('status', $okrObjective->status ?? 'draft') == $statusKey): echo 'selected'; endif; ?>><?php echo e(__($statusLabel)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Progress %')); ?></label><input type="number" step="0.01" min="0" max="100" name="progress" class="form-control" value="<?php echo e(old('progress', $okrObjective->progress ?? 0)); ?>"></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('Start date')); ?></label><input type="date" name="start_date" class="form-control" value="<?php echo e(old('start_date', $okrObjective->start_date ?? '')); ?>"></div>
    <div class="col-md-3 mb-3"><label class="form-label"><?php echo e(__('End date')); ?></label><input type="date" name="end_date" class="form-control" value="<?php echo e(old('end_date', $okrObjective->end_date ?? '')); ?>"></div>
    <div class="col-md-12 mb-3"><label class="form-label"><?php echo e(__('Description')); ?></label><textarea name="description" class="form-control" rows="4"><?php echo e(old('description', $okrObjective->description ?? '')); ?></textarea></div>
</div>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/okr_objectives/_form.blade.php ENDPATH**/ ?>