<?php echo e(Form::open(['route' => 'hospital-admissions.store', 'method' => 'post'])); ?>

<div class="modal-body"><div class="row">
    <div class="col-md-6"><label class="form-label"><?php echo e(__('Patient')); ?></label><select name="patient_id" class="form-control" required><option value=""><?php echo e(__('Select patient')); ?></option><?php $__currentLoopData = $patients; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $patient): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($patient->id); ?>"><?php echo e($patient->first_name); ?> <?php echo e($patient->last_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6"><label class="form-label"><?php echo e(__('Doctor')); ?></label><select name="attending_doctor_id" class="form-control"><option value=""><?php echo e(__('Select doctor')); ?></option><?php $__currentLoopData = $doctors; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $doctor): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($doctor->id); ?>"><?php echo e($doctor->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6 mt-2"><label class="form-label"><?php echo e(__('Room')); ?></label><select name="room_id" class="form-control"><option value=""><?php echo e(__('Select room')); ?></option><?php $__currentLoopData = $rooms; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $room): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($room->id); ?>"><?php echo e($room->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6 mt-2"><label class="form-label"><?php echo e(__('Bed')); ?></label><select name="bed_id" class="form-control"><option value=""><?php echo e(__('Select bed')); ?></option><?php $__currentLoopData = $beds; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $bed): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($bed->id); ?>"><?php echo e(optional($bed->room)->name); ?> / <?php echo e($bed->bed_number); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6 mt-2"><?php echo e(Form::label('admission_date', __('Admission Date'), ['class' => 'form-label'])); ?><?php echo e(Form::datetimeLocal('admission_date', now()->format('Y-m-d\TH:i'), ['class' => 'form-control'])); ?></div>
    <div class="col-md-6 mt-2"><?php echo e(Form::label('status', __('Status'), ['class' => 'form-label'])); ?><?php echo e(Form::select('status', ['admitted' => __('Admitted'), 'observation' => __('Observation'), 'discharged' => __('Discharged')], 'admitted', ['class' => 'form-control'])); ?></div>
    <div class="col-md-12 mt-2"><?php echo e(Form::label('reason', __('Reason'), ['class' => 'form-label'])); ?><?php echo e(Form::text('reason', null, ['class' => 'form-control'])); ?></div>
    <div class="col-md-12 mt-2"><?php echo e(Form::label('diagnosis', __('Diagnosis'), ['class' => 'form-label'])); ?><?php echo e(Form::textarea('diagnosis', null, ['class' => 'form-control', 'rows' => 2])); ?></div>
    <div class="col-md-12 mt-2"><?php echo e(Form::label('care_plan', __('Care Plan'), ['class' => 'form-label'])); ?><?php echo e(Form::textarea('care_plan', null, ['class' => 'form-control', 'rows' => 2])); ?></div>
</div></div>
<div class="modal-footer"><input type="button" value="<?php echo e(__('Cancel')); ?>" class="btn btn-secondary" data-bs-dismiss="modal"><input type="submit" value="<?php echo e(__('Create')); ?>" class="btn btn-primary"></div>
<?php echo e(Form::close()); ?>

<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/hospital_admission/create.blade.php ENDPATH**/ ?>