<form method="POST" action="<?php echo e(route('vendor-ratings.update', $vendorRating)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?>
    <div class="row">
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Vendor')); ?></label><select name="vender_id" class="form-control"><?php $__currentLoopData = $venders; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>" <?php if((int) $vendorRating->vender_id === (int) $id): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Period')); ?></label><input type="text" name="period_label" value="<?php echo e($vendorRating->period_label); ?>" class="form-control" required></div>
        <div class="col-md-3 form-group"><label class="form-label"><?php echo e(__('Quality')); ?></label><input type="number" step="0.01" name="quality_score" value="<?php echo e($vendorRating->quality_score); ?>" class="form-control"></div>
        <div class="col-md-3 form-group"><label class="form-label"><?php echo e(__('Delivery')); ?></label><input type="number" step="0.01" name="delivery_score" value="<?php echo e($vendorRating->delivery_score); ?>" class="form-control"></div>
        <div class="col-md-3 form-group"><label class="form-label"><?php echo e(__('Cost')); ?></label><input type="number" step="0.01" name="cost_score" value="<?php echo e($vendorRating->cost_score); ?>" class="form-control"></div>
        <div class="col-md-3 form-group"><label class="form-label"><?php echo e(__('Service')); ?></label><input type="number" step="0.01" name="service_score" value="<?php echo e($vendorRating->service_score); ?>" class="form-control"></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>" <?php if($vendorRating->status === $key): echo 'selected'; endif; ?>><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Notes')); ?></label><textarea name="notes" class="form-control" rows="3"><?php echo e($vendorRating->notes); ?></textarea></div>
    </div>
    <div class="text-end"><button type="submit" class="btn btn-primary"><?php echo e(__('Update')); ?></button></div>
</form>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/vendor_ratings/edit.blade.php ENDPATH**/ ?>