<?php $__env->startSection('page-title'); ?><?php echo e(__('CMDB')); ?><?php $__env->stopSection(); ?>
<?php $__env->startSection('breadcrumb'); ?><li class="breadcrumb-item"><a href="<?php echo e(route('dashboard')); ?>"><?php echo e(__('Dashboard')); ?></a></li><li class="breadcrumb-item"><?php echo e(__('CMDB')); ?></li><?php $__env->stopSection(); ?>
<?php $__env->startSection('action-btn'); ?>
<div class="float-end d-flex"><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('create configuration item')): ?><a href="#" data-url="<?php echo e(route('configuration-items.create')); ?>" data-size="lg" data-ajax-popup="true" data-title="<?php echo e(__('Create Configuration Item')); ?>" class="btn btn-sm btn-primary"><i class="ti ti-plus"></i></a><?php endif; ?></div>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('content'); ?>
<div class="card"><div class="card-body table-border-style"><div class="table-responsive"><table class="table datatable"><thead><tr><th><?php echo e(__('Item')); ?></th><th><?php echo e(__('Type')); ?></th><th><?php echo e(__('Owner')); ?></th><th><?php echo e(__('Asset')); ?></th><th><?php echo e(__('Criticality')); ?></th><th><?php echo e(__('Status')); ?></th><th width="220px"><?php echo e(__('Action')); ?></th></tr></thead><tbody><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td><div><?php echo e($item->name); ?></div><small class="text-muted"><?php echo e($item->asset_tag ?: '-'); ?></small></td><td><?php echo e($item->ci_type ?: '-'); ?></td><td><?php echo e(optional($item->owner)->name ?: '-'); ?></td><td><?php echo e(optional($item->asset)->name ?: '-'); ?></td><td><?php echo e(ucfirst($item->criticality ?: '-')); ?></td><td><?php echo e(ucfirst($item->status)); ?></td><td class="Action"><div class="action-btn me-2"><a href="<?php echo e(route('configuration-items.show', $item->id)); ?>" class="mx-3 btn btn-sm align-items-center bg-warning"><i class="ti ti-eye text-white"></i></a></div><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('edit configuration item')): ?><div class="action-btn me-2"><a href="#" data-url="<?php echo e(route('configuration-items.edit', $item->id)); ?>" data-size="lg" data-ajax-popup="true" data-title="<?php echo e(__('Edit Configuration Item')); ?>" class="mx-3 btn btn-sm align-items-center bg-info"><i class="ti ti-pencil text-white"></i></a></div><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('delete configuration item')): ?><div class="action-btn"><?php echo Form::open(['method' => 'DELETE', 'route' => ['configuration-items.destroy', $item->id], 'id' => 'delete-form-ci-' . $item->id]); ?><a href="#" class="mx-3 btn btn-sm align-items-center bs-pass-para bg-danger" data-confirm="<?php echo e(__('Are You Sure?') . '|' . __('This action can not be undone. Do you want to continue?')); ?>" data-confirm-yes="document.getElementById('delete-form-ci-<?php echo e($item->id); ?>').submit();"><i class="ti ti-trash text-white"></i></a><?php echo Form::close(); ?></div><?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/configuration_items/index.blade.php ENDPATH**/ ?>