<form method="POST" action="<?php echo e(route('lims-records.store')); ?>"><?php echo csrf_field(); ?>
    <div class="row">
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Sample Code')); ?></label><input type="text" name="sample_code" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Test Type')); ?></label><input type="text" name="test_type" class="form-control" required></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Product')); ?></label><select name="product_service_id" class="form-control"><option value=""><?php echo e(__('None')); ?></option><?php $__currentLoopData = $products; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>"><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Approver')); ?></label><select name="approved_by" class="form-control"><option value=""><?php echo e(__('None')); ?></option><?php $__currentLoopData = $employees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $id => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($id); ?>"><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Lot Reference')); ?></label><input type="text" name="lot_reference" class="form-control"></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Status')); ?></label><select name="status" class="form-control"><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>"><?php echo e(__($label)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6 form-group"><label class="form-label"><?php echo e(__('Tested At')); ?></label><input type="datetime-local" name="tested_at" class="form-control"></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Result Summary')); ?></label><textarea name="result_summary" class="form-control" rows="3"></textarea></div>
        <div class="col-12 form-group"><label class="form-label"><?php echo e(__('Notes')); ?></label><textarea name="notes" class="form-control" rows="3"></textarea></div>
    </div><div class="text-end"><button type="submit" class="btn btn-primary"><?php echo e(__('Create')); ?></button></div>
</form>
<?php /**PATH /Users/mohamedyassine/Downloads/Nouveau dossier contenant des éléments 5/erpgosaas-81nulled/codecanyon-33263426-erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm/main-file/resources/views/lims_records/create.blade.php ENDPATH**/ ?>